### ISSUE TITLE
#object[TypeError TypeError: Cannot read property 'insertBefore' of null]

### ISSUE THREAD

**Issue by YannickTemplay** [oschmid/roam-plugins#3]
Hello,

I get the error message  _**#object[TypeError TypeError: Cannot read property 'insertBefore' of null]**_ on the top of the Roam window. 

It uses to work quite well and now I got this error systematically on my main graph while the same plugin code works fine in a second (simpler) graph so it maybe an error processing some page names or something like that?

**Comment by oschmid** [comment]
Have you tried the latest version of the code? This sounds like the recently fixed issue #1

**Comment by YannickTemplay** [comment]
Yes. Most likely. Many thanks.
