### ISSUE TITLE
Random Page Plugin doesn't work anymore

### ISSUE THREAD

**Issue by dcervenkov** [oschmid/roam-plugins#4]
Roam's DOM changed and the `topbar` and `dots` queries need to be updated.

**Comment by oschmid** [comment]
Thanks for letting me know. Fixed in 171a0c6

**Comment by dcervenkov** [comment]
Thanks for the quick fix! Unfortunately, there are two problems.
1. `setTimeout(randomPagePlugin, 0);` causes the button to appear for a moment and then disappear. Reverting to the previous `setTimeout(randomPagePlugin, 1000);` fixes the issue.
2. A cosmetic issue - there should be a `rm-topbar__spacer-sm` between the search box and the button.

**Comment by oschmid** [comment]
No problem! I've fixed the second issue but I can't seem to reproduce the first one. The button never disappears for me. Which browser/OS are you using?

**Comment by dcervenkov** [comment]
I'm using Chromium 88.0.4324.146 on Linux 5.4.0 (Ubuntu 18.04 related). I just tried with Firefox 85.0 and can see the same problem. Setting the timeout to 1000 ms fixes the issue in both browsers.
