### ISSUE TITLE
The hotkey funtion isn't working for me on on the "random page" plugin.

### ISSUE THREAD

**Issue by Etyre** [oschmid/roam-plugins#5]
I'm not sure why. 

I tried some other variations, and I tried simply using the code from the last working version (many months old, I'm slow to update), but nothing has worked yet. 

Basically when I hit the relevant keys, nothing seems to happen.

I'm on a mac, OSX Big Sur, using roam in firefox (but it doesn't work in Chrome, either).

Any suggestions?

**Comment by Etyre** [comment]
When I straight up swap out the current version of the function for this old version,

`  function addKeyboardShortcut() {
    document.onkeyup = function(e) {
      var key = e.which || e.keyCode;
      if (e.altKey && key === shortcut) {
        goToRandomPage(e);
      }
    }
  }`

I get this weird behavior where the URL changes, for a split second, before reverting back to the page that I was on. Not sure what's up with that, or if it is related to the hot key not working at all, for me, in the new version.

**Comment by oschmid** [comment]
Thanks for letting me know. I'm definitely seeing the same bug in Linux/Chrome. But it's an odd one: event though the key event is triggering the same code as clicking the button, navigation is only happening with the later. It might be a browser security policy against programmatic navigation..? I'll need to keep digging.

**Comment by oschmid** [comment]
Took a while but I figured it out @Etyre. Issue fixed in 98746cb287a04fb3a5e60788eabfbe5de1ed24b7
